name: Add-on lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: frenck/action-addon-linter@v2.21.1
        with:
          apparmor: false
          path: .